"""
Карта нормализации названий стран.

Формат: {alias: normalized_value}
- Ключи: все возможные варианты написания (нижний регистр)
- Значения: каноническое название (верхний регистр)
"""

COUNTRY_NORMALIZATION_MAP = {
    # --- СНГ И РОССИЯ ---
    "россия": "RUSSIA",
    "рф": "RUSSIA",
    "russian federation": "RUSSIA",
    "ru": "RUSSIA",
    "беларусь": "BELARUS",
    "белоруссия": "BELARUS",
    "by": "BELARUS",
    "казахстан": "KAZAKHSTAN",
    "kz": "KAZAKHSTAN",
    "армения": "ARMENIA",
    "am": "ARMENIA",
    "грузия": "GEORGIA",
    "ge": "GEORGIA",
    "узбекистан": "UZBEKISTAN",
    "uz": "UZBEKISTAN",
    "киргизия": "KYRGYZSTAN",
    "кыргызстан": "KYRGYZSTAN",
    "kg": "KYRGYZSTAN",
    "украина": "UKRAINE",
    "ua": "UKRAINE",

    # --- ЕВРОПА ---
    "германия": "GERMANY",
    "germany": "GERMANY",
    "deutschland": "GERMANY",
    "de": "GERMANY",
    "великобритания": "UNITED KINGDOM",
    "united kingdom": "UNITED KINGDOM",
    "england": "UNITED KINGDOM",
    "uk": "UNITED KINGDOM",
    "britain": "UNITED KINGDOM",
    "англия": "UNITED KINGDOM",
    "нидерланды": "NETHERLANDS",
    "netherlands": "NETHERLANDS",
    "holland": "NETHERLANDS",
    "голландия": "NETHERLANDS",
    "nl": "NETHERLANDS",
    "польша": "POLAND",
    "poland": "POLAND",
    "polska": "POLAND",
    "pl": "POLAND",
    "кипр": "CYPRUS",
    "cyprus": "CYPRUS",
    "cy": "CYPRUS",
    "сербия": "SERBIA",
    "serbia": "SERBIA",
    "rs": "SERBIA",
    "черногория": "MONTENEGRO",
    "montenegro": "MONTENEGRO",
    "me": "MONTENEGRO",
    "франция": "FRANCE",
    "france": "FRANCE",
    "fr": "FRANCE",
    "испания": "SPAIN",
    "spain": "SPAIN",
    "es": "SPAIN",
    "португалия": "PORTUGAL",
    "portugal": "PORTUGAL",
    "pt": "PORTUGAL",
    "италия": "ITALY",
    "italy": "ITALY",
    "it": "ITALY",
    "швейцария": "SWITZERLAND",
    "switzerland": "SWITZERLAND",
    "ch": "SWITZERLAND",
    "бельгия": "BELGIUM",
    "belgium": "BELGIUM",
    "be": "BELGIUM",
    "грецесия": "GREECE",
    "greece": "GREECE",
    "gr": "GREECE",
    "румыния": "ROMANIA",
    "romania": "ROMANIA",
    "ro": "ROMANIA",
    "венгрия": "HUNGARY",
    "hungary": "HUNGARY",
    "hu": "HUNGARY",
    "чехия": "CZECH REPUBLIC",
    "czech republic": "CZECH REPUBLIC",
    "czechia": "CZECH REPUBLIC",

    # --- СЕВЕРНАЯ АМЕРИКА ---
    "сша": "UNITED STATES",
    "usa": "UNITED STATES",
    "united states": "UNITED STATES",
    "us": "UNITED STATES",
    "америка": "UNITED STATES",
    "канада": "CANADA",
    "ca": "CANADA",

    # --- АЗИЯ И БЛИЖНИЙ ВОСТОК ---
    "оаэ": "UAE",
    "emirates": "UAE",
    "united arab emirates": "UAE",
    "дубай": "UAE",
    "израиль": "ISRAEL",
    "il": "ISRAEL",
    "турция": "TURKEY",
    "tr": "TURKEY",
    "türkiye": "TURKEY",
    "таиланд": "THAILAND",
    "тайланд": "THAILAND",
    "th": "THAILAND",
    "сингапур": "SINGAPORE",
    "sg": "SINGAPORE",
    "китай": "CHINA",
    "cn": "CHINA",
    "япония": "JAPAN",
    "jp": "JAPAN",
    "южная корея": "SOUTH KOREA",
    "south korea": "SOUTH KOREA",
    "kr": "SOUTH KOREA",
    "индия": "INDIA",
    "in": "INDIA",
    "индонезия": "INDONESIA",
    "id": "INDONESIA",
    "тайвань": "TAIWAN",
    "tw": "TAIWAN",
    "гонконг": "HONG KONG",
    "hk": "HONG KONG",

    # --- ДРУГОЕ ---
    "австралия": "AUSTRALIA",
    "au": "AUSTRALIA",
    "новая зеландия": "NEW ZEALAND",
    "nz": "NEW ZEALAND",
    "бразилия": "BRAZIL",
    "br": "BRAZIL",
    "мексика": "MEXICO",
    "mx": "MEXICO",
    "южная африка": "SOUTH AFRICA",
    "za": "SOUTH AFRICA",
}
