# =====================================================================
# [Пункт 15] Импликации навыков: если знаешь X, то Y тоже подразумевается
# =====================================================================

SKILL_IMPLIES = {
    "pandas": ["python"],
    "numpy": ["python"],
    "scipy": ["python"],
    "matplotlib": ["python"],
    "seaborn": ["python"],
    "plotly": ["python"],
    "scikit-learn": ["python"],
    "sklearn": ["python"],
    "pytorch": ["python"],
    "tensorflow": ["python"],
    "keras": ["python"],
    "jax": ["python"],
    "xgboost": ["python"],
    "lightgbm": ["python"],
    "catboost": ["python"],
    "fastapi": ["python"],
    "flask": ["python"],
    "django": ["python"],
    "pyspark": ["python", "spark"],
    "airflow": ["python"],
    "dbt": ["sql"],
    "postgresql": ["sql"],
    "postgres": ["sql"],
    "mysql": ["sql"],
    "mssql": ["sql"],
    "sqlite": ["sql"],
    "mariadb": ["sql"],
    "oracle": ["sql"],
    "cockroachdb": ["sql"],
    "clickhouse": ["sql"],
    "timescaledb": ["sql"],
    "bigquery": ["sql"],
    "redshift": ["sql"],
    "snowflake": ["sql"],
    "presto": ["sql"],
    "trino": ["sql"],
    "hive": ["sql"],
    "react native": ["react", "javascript"],
    "nextjs": ["react", "javascript"],
    "nuxt": ["vue", "javascript"],
    "express": ["javascript", "node.js"],
    "vue": ["javascript"],
    "angular": ["javascript", "typescript"],
    "react": ["javascript"],
    "typescript": ["javascript"],
    "spring boot": ["java", "spring"],
    "spring": ["java"],
    "kotlin": ["java"],
    "rails": ["ruby"],
    "laravel": ["php"],
    "swiftui": ["swift"],
    "jetpack compose": ["kotlin"],
    "flutter": ["dart"],
    "k8s": ["kubernetes"],
    "golang": ["go"],
    "helm": ["kubernetes"],
    "istio": ["kubernetes"],
    "kubeflow": ["kubernetes", "python"],
    "sagemaker": ["aws", "python"],
    "vertex ai": ["gcp", "python"],
    "databricks": ["spark", "python", "sql"],
    "mlflow": ["python"],
    "wandb": ["python"],
    "langchain": ["python"],
    "llamaindex": ["python"],
    "huggingface": ["python"],
    "opencv": ["python"],
    "spacy": ["python"],
    "nltk": ["python"],
    "gensim": ["python"],
    "google cloud": ["gcp"],
    "github actions": ["git"],
    "gitlab ci": ["git"],
}


# =====================================================================
# Карта синонимов навыков -> каноническое имя
# =====================================================================

SKILL_SYNONYMS = {
    # --- Programming Languages ---
    "python": "Python", "py": "Python", "python3": "Python",
    "питон": "Python", "пайтон": "Python", "пайтн": "Python",
    "java": "Java", "джава": "Java",
    "javascript": "JavaScript", "js": "JavaScript",
    "джаваскрипт": "JavaScript", "жс": "JavaScript",
    "typescript": "TypeScript", "ts": "TypeScript", "тайпскрипт": "TypeScript",
    "scala": "Scala", "скала": "Scala",
    "go": "Go", "golang": "Go", "голанг": "Go",
    "rust": "Rust", "раст": "Rust",
    "r_lang": "R",
    "c++": "C++", "cpp": "C++", "си плюс плюс": "C++", "плюсы": "C++",
    "c#": "C#", "csharp": "C#", "c sharp": "C#", "си шарп": "C#",
    "swift": "Swift", "свифт": "Swift",
    "kotlin": "Kotlin", "котлин": "Kotlin",
    "ruby": "Ruby", "руби": "Ruby",
    "php": "PHP", "пхп": "PHP",
    "perl": "Perl", "перл": "Perl",
    "dart": "Dart", "дарт": "Dart",
    "julia": "Julia", "джулия": "Julia",
    "matlab": "MATLAB", "матлаб": "MATLAB",
    "lua": "Lua", "луа": "Lua",
    ".net": ".NET", "dotnet": ".NET", "дотнет": ".NET",
    "solidity": "Solidity",
    "objective-c": "Objective-C", "objc": "Objective-C",
    "haskell": "Haskell", "хаскель": "Haskell", "хаскелл": "Haskell",
    "elixir": "Elixir", "эликсир": "Elixir",
    "clojure": "Clojure", "кложур": "Clojure",
    "groovy": "Groovy", "груви": "Groovy",

    # --- Databases ---
    "sql": "SQL", "скл": "SQL", "скуэль": "SQL", "эскуэль": "SQL",
    "postgresql": "PostgreSQL", "postgres": "PostgreSQL",
    "постгрес": "PostgreSQL", "постгря": "PostgreSQL", "пг": "PostgreSQL", "pg": "PostgreSQL",
    "mysql": "MySQL", "мускул": "MySQL", "мускл": "MySQL",
    "mongodb": "MongoDB", "монго": "MongoDB", "монга": "MongoDB",
    "redis": "Redis", "редис": "Redis",
    "elasticsearch": "Elasticsearch", "эластик": "Elasticsearch", "elastic": "Elastic",
    "cassandra": "Cassandra", "кассандра": "Cassandra",
    "dynamodb": "DynamoDB", "динамо": "DynamoDB",
    "neo4j": "Neo4j",
    "clickhouse": "ClickHouse", "клик": "ClickHouse", "кликхаус": "ClickHouse", "ch": "ClickHouse",
    "sqlite": "SQLite",
    "mariadb": "MariaDB",
    "oracle": "Oracle", "оракл": "Oracle",
    "cockroachdb": "CockroachDB",
    "supabase": "Supabase", "firebase": "Firebase",
    "mssql": "MS SQL", "ms sql": "MS SQL", "sql server": "MS SQL",
    "timescaledb": "TimescaleDB", "influxdb": "InfluxDB",
    "couchdb": "CouchDB",

    # --- Cloud ---
    "aws": "AWS", "amazon web services": "AWS", "амазон": "AWS",
    "azure": "Azure", "азур": "Azure", "ажур": "Azure",
    "gcp": "GCP", "google cloud": "GCP", "гугл клауд": "GCP",
    "heroku": "Heroku", "digitalocean": "DigitalOcean",
    "cloudflare": "Cloudflare", "vercel": "Vercel", "netlify": "Netlify",

    # --- DevOps / Infra ---
    "docker": "Docker", "докер": "Docker",
    "kubernetes": "Kubernetes", "k8s": "Kubernetes",
    "кубер": "Kubernetes", "кубернетис": "Kubernetes", "кубернетес": "Kubernetes", "к8с": "Kubernetes",
    "terraform": "Terraform", "терраформ": "Terraform", "tf": "Terraform",
    "ansible": "Ansible", "ансибл": "Ansible", "ансибль": "Ansible",
    "jenkins": "Jenkins", "дженкинс": "Jenkins",
    "github actions": "GitHub Actions", "гитхаб экшнс": "GitHub Actions",
    "gitlab ci": "GitLab CI", "гитлаб": "GitLab CI",
    "circleci": "CircleCI", "argocd": "ArgoCD",
    "helm": "Helm", "хелм": "Helm",
    "istio": "Istio",
    "consul": "Consul", "vault": "Vault",
    "nginx": "Nginx", "энджинкс": "Nginx",
    "apache": "Apache", "caddy": "Caddy",
    "linux": "Linux", "линукс": "Linux", "линакс": "Linux",
    "bash": "Bash", "баш": "Bash",
    "shell": "Shell", "powershell": "PowerShell",

    # --- Big Data ---
    "spark": "Apache Spark", "pyspark": "Apache Spark",
    "спарк": "Apache Spark", "пайспарк": "Apache Spark",
    "kafka": "Apache Kafka", "кафка": "Apache Kafka",
    "airflow": "Apache Airflow", "эирфлоу": "Apache Airflow", "аирфлоу": "Apache Airflow",
    "dbt": "dbt",
    "snowflake": "Snowflake", "сноуфлейк": "Snowflake",
    "bigquery": "BigQuery", "бигквери": "BigQuery", "bq": "BigQuery",
    "redshift": "Redshift", "редшифт": "Redshift",
    "databricks": "Databricks", "датабрикс": "Databricks",
    "flink": "Apache Flink", "флинк": "Apache Flink",
    "hive": "Hive", "хайв": "Hive",
    "presto": "Presto", "trino": "Trino",
    "delta lake": "Delta Lake", "iceberg": "Iceberg",
    "dask": "Dask", "ray": "Ray",
    "prefect": "Prefect", "dagster": "Dagster",
    "luigi": "Luigi", "mage": "Mage", "nifi": "NiFi",

    # --- ML / AI ---
    "pytorch": "PyTorch", "пайторч": "PyTorch", "торч": "PyTorch",
    "tensorflow": "TensorFlow", "тензорфлоу": "TensorFlow",
    "keras": "Keras", "керас": "Keras",
    "jax": "JAX",
    "scikit-learn": "Scikit-learn", "sklearn": "Scikit-learn",
    "скайлерн": "Scikit-learn", "сайкитлерн": "Scikit-learn",
    "xgboost": "XGBoost", "lightgbm": "LightGBM", "catboost": "CatBoost",
    "huggingface": "Hugging Face", "хаггингфейс": "Hugging Face", "hf": "Hugging Face",
    "langchain": "LangChain", "лангчейн": "LangChain",
    "llamaindex": "LlamaIndex",
    "opencv": "OpenCV",
    "spacy": "spaCy", "спейси": "spaCy",
    "nltk": "NLTK",
    "gensim": "Gensim",
    "pandas": "Pandas", "пандас": "Pandas", "pd": "Pandas",
    "numpy": "NumPy", "нампай": "NumPy", "np": "NumPy",
    "scipy": "SciPy", "сайпай": "SciPy",
    "matplotlib": "Matplotlib", "матплотлиб": "Matplotlib", "plt": "Matplotlib",
    "seaborn": "Seaborn", "сиборн": "Seaborn",
    "plotly": "Plotly",
    "transformers": "Transformers",
    "stable diffusion": "Stable Diffusion",
    "onnx": "ONNX", "tensorrt": "TensorRT",
    "pillow": "Pillow",

    # --- MLOps ---
    "mlflow": "MLflow", "wandb": "W&B", "dvc": "DVC",
    "kubeflow": "Kubeflow", "кубефлоу": "Kubeflow",
    "sagemaker": "SageMaker", "сейджмейкер": "SageMaker",
    "vertex ai": "Vertex AI",
    "bentoml": "BentoML", "seldon": "Seldon", "triton": "Triton",
    "feast": "Feast", "great expectations": "Great Expectations",

    # --- Web / Backend ---
    "fastapi": "FastAPI", "фастапи": "FastAPI",
    "flask": "Flask", "фласк": "Flask",
    "django": "Django", "джанго": "Django",
    "express": "Express", "экспресс": "Express",
    "spring": "Spring", "спринг": "Spring",
    "spring boot": "Spring Boot", "спринг бут": "Spring Boot",
    "rails": "Rails", "рельсы": "Rails",
    "laravel": "Laravel", "ларавел": "Laravel",
    "nextjs": "Next.js", "next.js": "Next.js", "некст": "Next.js",
    "nuxt": "Nuxt", "nuxtjs": "Nuxt",
    "svelte": "Svelte", "remix": "Remix",
    "graphql": "GraphQL", "графкл": "GraphQL",
    "rest api": "REST API", "рест апи": "REST API", "restful": "REST API",
    "grpc": "gRPC",
    "websocket": "WebSocket", "вебсокет": "WebSocket",

    # --- Frontend ---
    "react": "React", "реакт": "React", "reactjs": "React",
    "vue": "Vue", "вью": "Vue", "vuejs": "Vue",
    "angular": "Angular", "ангуляр": "Angular", "ангулар": "Angular",
    "tailwind": "Tailwind CSS", "тейлвинд": "Tailwind CSS",
    "bootstrap": "Bootstrap", "бутстрап": "Bootstrap",
    "webpack": "Webpack", "вебпак": "Webpack",
    "vite": "Vite", "storybook": "Storybook",

    # --- Mobile ---
    "react native": "React Native", "react-native": "React Native",
    "flutter": "Flutter", "флаттер": "Flutter",
    "swiftui": "SwiftUI", "jetpack compose": "Jetpack Compose",

    # --- Tools ---
    "git": "Git", "гит": "Git",
    "jira": "Jira", "джира": "Jira",
    "confluence": "Confluence", "конфлюенс": "Confluence",
    "figma": "Figma", "фигма": "Figma",
    "postman": "Postman", "постман": "Postman",
    "notion": "Notion", "ноушен": "Notion", "ноушн": "Notion",
    "slack": "Slack", "слак": "Slack",
    "swagger": "Swagger", "свагер": "Swagger",
    "datadog": "Datadog", "grafana": "Grafana", "графана": "Grafana",
    "prometheus": "Prometheus", "прометеус": "Prometheus",
    "splunk": "Splunk", "kibana": "Kibana",
    "sentry": "Sentry", "сентри": "Sentry",
    "pagerduty": "PagerDuty",
    "superset": "Superset",

    # --- BI ---
    "power bi": "Power BI", "пауэр би": "Power BI", "powerbi": "Power BI",
    "tableau": "Tableau", "табло": "Tableau",
    "looker": "Looker", "лукер": "Looker",
    "metabase": "Metabase", "метабейс": "Metabase",
    "excel": "Excel", "эксель": "Excel", "ms excel": "Excel",
    "google sheets": "Google Sheets", "гугл таблицы": "Google Sheets",

    # --- Methodologies ---
    "agile": "Agile", "эджайл": "Agile", "аджайл": "Agile",
    "scrum": "Scrum", "скрам": "Scrum",
    "kanban": "Kanban", "канбан": "Kanban",
    "devops": "DevOps", "девопс": "DevOps",
    "mlops": "MLOps", "млопс": "MLOps",
    "ci/cd": "CI/CD", "cicd": "CI/CD", "ci-cd": "CI/CD",
    "microservices": "Microservices", "микросервисы": "Microservices",
    "tdd": "TDD", "bdd": "BDD", "soa": "SOA",
    "etl": "ETL", "elt": "ELT",

    # --- Concepts (from resumes) ---
    "machine learning": "Machine Learning", "ml": "Machine Learning",
    "машинное обучение": "Machine Learning", "мл": "Machine Learning",
    "deep learning": "Deep Learning", "dl": "Deep Learning",
    "глубокое обучение": "Deep Learning",
    "natural language processing": "NLP", "nlp": "NLP",
    "обработка естественного языка": "NLP", "нлп": "NLP",
    "computer vision": "Computer Vision", "cv": "Computer Vision",
    "компьютерное зрение": "Computer Vision",
    "large language models": "LLM", "llm": "LLM", "llms": "LLM",
    "большие языковые модели": "LLM", "бям": "LLM",
    "generative ai": "Generative AI", "genai": "Generative AI",
    "генеративный ии": "Generative AI",
    "retrieval augmented generation": "RAG", "rag": "RAG",
    "prompt engineering": "Prompt Engineering",
    "промпт инжиниринг": "Prompt Engineering",
    "data science": "Data Science", "ds": "Data Science",
    "дата сайенс": "Data Science",
    "data engineering": "Data Engineering", "de": "Data Engineering",
    "дата инжиниринг": "Data Engineering",
    "data analysis": "Data Analysis", "аналитика данных": "Data Analysis",
    "a/b testing": "A/B Testing", "а/б тестирование": "A/B Testing",
    "feature engineering": "Feature Engineering",
    "time series": "Time Series", "временные ряды": "Time Series",
    "recommender systems": "Recommender Systems",
    "рекомендательные системы": "Recommender Systems",

    # --- Node.js (special) ---
    "node.js": "Node.js", "nodejs": "Node.js", "нода": "Node.js", "ноджс": "Node.js",
}