CITY_NORMALIZATION_MAP = {
    # --- РОССИЯ (Твои + дополнения) ---
    "москва": "MOSCOW", "moscow": "MOSCOW", "msk": "MOSCOW", "мск": "MOSCOW",
    "санкт-петербург": "SAINT PETERSBURG", "st petersburg": "SAINT PETERSBURG", "петербург": "SAINT PETERSBURG", "спб": "SAINT PETERSBURG", "spb": "SAINT PETERSBURG",
    "новосибирск": "NOVOSIBIRSK", "nsk": "NOVOSIBIRSK", "нск": "NOVOSIBIRSK",
    "екатеринбург": "YEKATERINBURG", "yekaterinburg": "YEKATERINBURG", "екб": "YEKATERINBURG",
    "нижний новгород": "NIZHNY NOVGOROD", "казань": "KAZAN", "челябинск": "CHELYABINSK",
    "омск": "OMSK", "самара": "SAMARA", "ростов-на-дону": "ROSTOV-ON-DON", "уфа": "UFA",
    "красноярск": "KRASNOYARSK", "воронеж": "VORONEZH", "пермь": "PERM", "волгоград": "VOLGOGRAD",
    "краснодар": "KRASNODAR", "саратов": "SARATOV", "тюмень": "TYUMEN", "иркутск": "IRKUTSK",
    "хабаровск": "KHABAROVSK", "владивосток": "VLADIVOSTOK", "томск": "TOMSK",
    "калининград": "KALININGRAD", "сочи": "SOCHI", "иннополис": "INNOPOLIS",

    # --- США (Города и штаты) ---
    "new york": "NEW YORK", "nyc": "NEW YORK", "ny": "NEW YORK", "нью-йорк": "NEW YORK",
    "san francisco": "SAN FRANCISCO", "sf": "SAN FRANCISCO", "сан-франциско": "SAN FRANCISCO",
    "austin": "AUSTIN", "остин": "AUSTIN",
    "seattle": "SEATTLE", "сиэтл": "SEATTLE",
    "palo alto": "PALO ALTO", "mountain view": "MOUNTAIN VIEW", # Кремниевая долина
    "los angeles": "LOS ANGELES", "la": "LOS ANGELES",
    "boston": "BOSTON", "бостон": "BOSTON",
    "chicago": "CHICAGO", "чикаго": "CHICAGO",

    # --- КАНАДА ---
    "toronto": "TORONTO", "торонто": "TORONTO",
    "vancouver": "VANCOUVER", "ванкувер": "VANCOUVER",
    "montreal": "MONTREAL", "монреаль": "MONTREAL",
    "ottawa": "OTTAWA", "оттава": "OTTAWA",

    # --- ЕВРОПА (ИТ-хабы) ---
    "london": "LONDON", "лондон": "LONDON",
    "berlin": "BERLIN", "берлин": "BERLIN",
    "amsterdam": "AMSTERDAM", "амстердам": "AMSTERDAM",
    "paris": "PARIS", "париж": "PARIS",
    "warsaw": "WARSAW", "warszawa": "WARSAW", "варшава": "WARSAW",
    "belgrade": "BELGRADE", "beograd": "BELGRADE", "белград": "BELGRADE",
    "lisbon": "LISBON", "лиссабон": "LISBON",
    "limassol": "LIMASSOL", "лимасол": "LIMASSOL",
    "tbilisi": "TBILISI", "тбилиси": "TBILISI",
    "yerevan": "YEREVAN", "ереван": "YEREVAN",

    # --- АЗИЯ ---
    "dubai": "DUBAI", "дубай": "DUBAI",
    "singapore": "SINGAPORE", "сингапур": "SINGAPORE",
    "tel aviv": "TEL AVIV", "тел-авив": "TEL AVIV",
    "bangkok": "BANGKOK", "бангкок": "BANGKOK",
    "seoul": "SEOUL", "сеул": "SEOUL",
    "tokyo": "TOKYO", "токио": "TOKYO", 
    'astana': "ASTANA", "астана": "ASTANA",

    # --- ТИП РАБОТЫ ---
    "remote": "REMOTE", "удаленка": "REMOTE", "удаленно": "REMOTE", "anywhere": "REMOTE",

    "москва": "MOSCOW", "санкт-петербург": "SAINT PETERSBURG",
    "петербург": "SAINT PETERSBURG", "спб": "SAINT PETERSBURG",
    "новосибирск": "NOVOSIBIRSK", "екатеринбург": "YEKATERINBURG",
    "нижний новгород": "NIZHNY NOVGOROD", "казань": "KAZAN",
    "челябинск": "CHELYABINSK", "омск": "OMSK", "самара": "SAMARA",
    "ростов-на-дону": "ROSTOV-ON-DON", "уфа": "UFA",
    "красноярск": "KRASNOYARSK", "воронеж": "VORONEZH",
    "пермь": "PERM", "волгоград": "VOLGOGRAD", "краснодар": "KRASNODAR",
    "саратов": "SARATOV", "тюмень": "TYUMEN", "иркутск": "IRKUTSK",
    "хабаровск": "KHABAROVSK", "владивосток": "VLADIVOSTOK",
    "томск": "TOMSK", "калининград": "KALININGRAD", "сочи": "SOCHI",
    "ярославль": "YAROSLAVL", "тула": "TULA", "курск": "KURSK",
    "мурманск": "MURMANSK", "якутск": "YAKUTSK",

    # --- Россия / СНГ ---
    "москва": "MOSCOW",
    "moscow": "MOSCOW",
    "msk": "MOSCOW",
    "мск": "MOSCOW",

    "санкт-петербург": "SAINT PETERSBURG",
    "st petersburg": "SAINT PETERSBURG",
    "петербург": "SAINT PETERSBURG",
    "спб": "SAINT PETERSBURG",
    "spb": "SAINT PETERSBURG",

    "новосибирск": "NOVOSIBIRSK",
    "nsk": "NOVOSIBIRSK",
    "нск": "NOVOSIBIRSK",

    "екатеринбург": "YEKATERINBURG",
    "yekaterinburg": "YEKATERINBURG",
    "екб": "YEKATERINBURG",

    "нижний новгород": "NIZHNY NOVGOROD",
    "казань": "KAZAN",
    "челябинск": "CHELYABINSK",
    "омск": "OMSK",
    "самара": "SAMARA",
    "ростов-на-дону": "ROSTOV-ON-DON",
    "уфа": "UFA",
    "красноярск": "KRASNOYARSK",
    "воронеж": "VORONEZH",
    "пермь": "PERM",
    "волгоград": "VOLGOGRAD",
    "краснодар": "KRASNODAR",
    "саратов": "SARATOV",
    "тюмень": "TYUMEN",
    "иркутск": "IRKUTSK",
    "хабаровск": "KHABAROVSK",
    "владивосток": "VLADIVOSTOK",
    "томск": "TOMSK",
    "калининград": "KALININGRAD",
    "сочи": "SOCHI",
    "ярославль": "YAROSLAVL",
    "тула": "TULA",
    "курск": "KURSK",
    "мурманск": "MURMANSK",
    "якутск": "YAKUTSK",

    "алматы": "ALMATY",
    "almaty": "ALMATY",
    "минск": "MINSK",
    "minsk": "MINSK",
    "витебск": "VITEBSK",
    "vitebsk": "VITEBSK",

    # --- США ---
    "new york": "NEW YORK",
    "new york city": "NEW YORK",
    "nyc": "NEW YORK",
    "ny": "NEW YORK",
    "нью-йорк": "NEW YORK",

    "san francisco": "SAN FRANCISCO",
    "sf": "SAN FRANCISCO",
    "сан-франциско": "SAN FRANCISCO",

    "austin": "AUSTIN",
    "остин": "AUSTIN",

    "seattle": "SEATTLE",
    "сиэтл": "SEATTLE",

    "palo alto": "PALO ALTO",
    "mountain view": "MOUNTAIN VIEW",

    "los angeles": "LOS ANGELES",
    "la": "LOS ANGELES",

    "boston": "BOSTON",
    "бостон": "BOSTON",

    "chicago": "CHICAGO",
    "чикаго": "CHICAGO",

    "atlanta": "ATLANTA",
    "dallas": "DALLAS",
    "denver": "DENVER",
    "miami": "MIAMI",
    "houston": "HOUSTON",
    "philadelphia": "PHILADELPHIA",
    "pittsburgh": "PITTSBURGH",
    "san diego": "SAN DIEGO",
    "san jose": "SAN JOSE",
    "salt lake city": "SALT LAKE CITY",
    "jersey city": "JERSEY CITY",
    "raleigh": "RALEIGH",
    "arlington": "ARLINGTON",
    "cambridge": "CAMBRIDGE",
    "honolulu": "HONOLULU",
    "provo": "PROVO",
    "frisco": "FRISCO",
    "plano": "PLANO",
    "sunnyvale": "SUNNYVALE",
    "bellevue": "BELLEVUE",
    "kirkland": "KIRKLAND",
    "ann arbor": "ANN ARBOR",
    "berkeley": "BERKELEY",
    "saint louis": "SAINT LOUIS",
    "st louis": "SAINT LOUIS",
    "tysons": "TYSONS",
    "cottonwood heights": "COTTONWOOD HEIGHTS",

    # --- Канада ---
    "toronto": "TORONTO",
    "торонто": "TORONTO",
    "vancouver": "VANCOUVER",
    "ванкувер": "VANCOUVER",
    "montreal": "MONTREAL",
    "монреаль": "MONTREAL",
    "ottawa": "OTTAWA",
    "оттава": "OTTAWA",
    "north vancouver": "NORTH VANCOUVER",
    "new westminster": "NEW WESTMINSTER",
    "mississauga": "MISSISSAUGA",

    # --- Европа ---
    "london": "LONDON",
    "лондон": "LONDON",
    "berlin": "BERLIN",
    "берлин": "BERLIN",
    "amsterdam": "AMSTERDAM",
    "амстердам": "AMSTERDAM",
    "paris": "PARIS",
    "париж": "PARIS",
    "warsaw": "WARSAW",
    "warszawa": "WARSAW",
    "варшава": "WARSAW",
    "belgrade": "BELGRADE",
    "beograd": "BELGRADE",
    "белград": "BELGRADE",
    "lisbon": "LISBON",
    "лиссабон": "LISBON",
    "limassol": "LIMASSOL",
    "лимасол": "LIMASSOL",
    "tbilisi": "TBILISI",
    "тбилиси": "TBILISI",
    "yerevan": "YEREVAN",
    "ереван": "YEREVAN",
}